### PR TITLE
typography: color 0 needs to be a visible foreground

### PR DESCRIPTION
**Pull request by ghost**
typography: all fg/bgs need to be readable

    All of the foreground colors against the default background and
    similarly all fo the background colors against the default foreground
    need to be readable combinations.

    The confusion stems from the fact that ansi terminals have two extra
    colors to worry about: the default foreground and default background. In
    gruvbox.vim these are fg1 and bg0 respectively, but in ansi that means
    we have to avoid using these colors (fg1 and bg0) in the 16-color
    pallete, since the result would be invisible.

    To fix it, I've substituted fg3 for fg0 and bg3 for bg0 where they had
    been used in the 16-color pallete. In the original colors/gruvbox.vim
    you can find that these colors are indeed used alone (with default
    fore/background) so that's my precedent.

### CODE REVIEW

**Comment by wdomitrz** [comment]
It doesn't seem right. See:
https://github.com/morhetz/gruvbox/blob/bf2885a95efdad7bd5e4794dd0213917770d79b7/colors/gruvbox.vim#L171
https://github.com/morhetz/gruvbox/blob/bf2885a95efdad7bd5e4794dd0213917770d79b7/colors/gruvbox.vim#L201
Please feel free to reopen if that's not right, but please provide some source/explanation.

**Comment by ghost** [comment]
Okay yes, this is nonintuitive until you look at it.

Before:

image
image


After:

image
image

**Comment by ghost** [comment]
I don't think I have a way to reopen this.

**Comment by wdomitrz** [comment]
Thanks. I will try to reopen it and then merge

**Comment by ghost** [comment]
Thank you :D

I've since noticed that the "Terminal Colors for Neovim" section of the upstream gruvbox.vim has the same bug(s). I'll talk to them about it too.
https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L272

**Pull request closed without merging**
